baseURL = "https://example.com"
title = "LETNH - Blog"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "LETNH Tech blog"
  copyright = "Copyright Â© 2020 letnh"
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/"
    weight = 10

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true
